name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed activate_server.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: activate_server-exe
          path: dist/activate_server.exe
